output_folder: slides
deploy_folder: public/lectures/lec02
build_command: R -e "rmarkdown::render('index.Rmd', envir = new.env(), quiet=TRUE)"
repository: https://github.com/SussexPsychMethods/paas2020.git
